# 05 - BackTesting

In [3]:
# imports
import pandas as pd
import numpy as np
import joblib
import os

#notebook settings
pd.set_option('display.max_columns', None)

In [4]:
# load the model
# Load the model from the file
filename = os.path.join('..','models','final_model_pipeline.pkl')
loaded_model = joblib.load(filename)


In [5]:
# load X_test, y_test and back testing data
X_test = pd.read_csv(os.path.join('..','data','processed','X_test.csv'))
y_test = pd.read_csv(os.path.join('..','data','processed','y_test.csv'))
data_for_back_testing = pd.read_csv(os.path.join('..','data','processed','data_for_back_testing.csv'))

# make predictions
y_pred = loaded_model.predict(X_test)

In [6]:
X_test.head()

home_team    away_team  day_of_week  month  day_of_week_sin  \
0    man city       bolton            6      5    -2.449294e-16   
1     swansea     west ham            6     12    -2.449294e-16   
2   liverpool   man united            5     10    -8.660254e-01   
3       stoke  bournemouth            5     11    -8.660254e-01   
4  sunderland   man united            5      3    -8.660254e-01   

   day_of_week_cos     month_sin     month_cos  home_roll_3_avg_home_corners  \
0              1.0  5.000000e-01 -8.660254e-01                      6.000000   
1              1.0 -2.449294e-16  1.000000e+00                      3.666667   
2              0.5 -8.660254e-01  5.000000e-01                      8.333333   
3              0.5 -5.000000e-01  8.660254e-01                      6.000000   
4              0.5  1.000000e+00  6.123234e-17                      7.666667   

   away_roll_3_avg_home_corners  home_roll_3_avg_away_corners  \
0                      7.666667                      6.000000   
1                      6.666667                      5.666667   
2                      6.333333                      3.666667   
3                      4.333333                      4.666667   
4                      5.333333                      4.666667   

   away_roll_3_avg_away_corners  home_roll_3_avg_home_yellow_cards  \
0                      5.000000                           1.000000   
1                      3.333333                           2.333333   
2                      6.666667                           2.333333   
3                      5.666667                           2.000000   
4                      5.333333                           1.666667   

   away_roll_3_avg_home_yellow_cards  home_roll_3_avg_away_yellow_cards  \
0                           1.333333                           2.000000   
1                           2.000000                           1.666667   
2                           2.000000                           3.333333   
3                           1.666667                           1.666667   
4                           0.666667                           2.666667   

   away_roll_3_avg_away_yellow_cards  home_roll_3_avg_home_red_cards  \
0                           2.333333                             0.0   
1                           0.666667                             0.0   
2                           0.666667                             0.0   
3                           2.000000                             0.0   
4                           1.666667                             0.0   

   away_roll_3_avg_home_red_cards  home_roll_3_avg_away_red_cards  \
0                        0.000000                        0.000000   
1                        0.000000                        0.000000   
2                        0.000000                        0.000000   
3                        0.333333                        0.000000   
4                        0.000000                        0.666667   

   away_roll_3_avg_away_red_cards  home_roll_3_avg_ratio_h_a_shots  \
0                        0.000000                         0.707158   
1                        0.333333                         0.615278   
2                        0.000000                         1.478211   
3                        0.000000                         1.394661   
4                        0.000000                         1.555556   

   away_roll_3_avg_ratio_h_a_shots  home_roll_3_avg_ratio_h_a_fouls  \
0                         2.342857                         1.041667   
1                         2.344444                         0.883319   
2                         1.296037                         1.543651   
3                         1.848485                         0.653846   
4                         1.970085                         0.701465   

   away_roll_3_avg_ratio_h_a_fouls  home_roll_3_avg_ratio_a_h_shots  \
0                         0.944258                         1.458689   
1                  

In [7]:
# what are the probability of the model predicting the target variable
y_pred_proba = loaded_model.predict_proba(X_test)
display(y_pred_proba)

# what are the team names that goint to win
y_pred = loaded_model.predict(X_test)
display(y_pred)

array([[8.7662295e-02, 4.8617385e-02, 8.6372030e-01],
       [4.4561982e-01, 2.1648605e-01, 3.3789405e-01],
       [1.6188450e-01, 5.1269239e-01, 3.2542315e-01],
       ...,
       [1.2289421e-01, 5.1314764e-02, 8.2579100e-01],
       [6.9481385e-01, 2.7257982e-01, 3.2606330e-02],
       [1.6545047e-04, 7.6585211e-04, 9.9906868e-01]], dtype=float32)

array([2, 0, 1, ..., 2, 0, 2])

In [8]:
print(data_for_back_testing.shape)
data_for_back_testing.head()

(7330, 3)


implied_home_win_prob  implied_draw_prob  implied_away_win_prob
0               0.404145           0.286010               0.309845
1               0.185958           0.273467               0.540575
2               0.391387           0.285412               0.323201
3               0.540575           0.273467               0.185958
4               0.323341           0.289997               0.386662

In [9]:
y_pred_proba

array([[8.7662295e-02, 4.8617385e-02, 8.6372030e-01],
       [4.4561982e-01, 2.1648605e-01, 3.3789405e-01],
       [1.6188450e-01, 5.1269239e-01, 3.2542315e-01],
       ...,
       [1.2289421e-01, 5.1314764e-02, 8.2579100e-01],
       [6.9481385e-01, 2.7257982e-01, 3.2606330e-02],
       [1.6545047e-04, 7.6585211e-04, 9.9906868e-01]], dtype=float32)

In [10]:
# Create a DataFrame to store team names and y_true values
team_names = X_test.loc[:, ['home_team', 'away_team']].copy()

#add the tru labels
team_names['true_results'] = y_test

# Add predicted results to the DataFrame decoded from the label encoding
team_names['predicted_results'] = y_pred


# Unpack y_pred_proba (probabilities for [Away, Draw, Home])
team_names[['away_prob', 'draw_prob', 'home_prob']] = pd.DataFrame(y_pred_proba, index=team_names.index)

# Ensure index alignment between team_names and data_for_back_testing for implied probabilities
team_names[['implied_home_win_prob', 'implied_draw_prob', 'implied_away_win_prob']] = data_for_back_testing.loc[team_names.index, ['implied_home_win_prob', 'implied_draw_prob', 'implied_away_win_prob']]

# Reorder columns for better readability
team_names = team_names[['home_team', 'away_team', 'true_results','predicted_results', 
                         'home_prob', 'draw_prob', 'away_prob', 
                         'implied_home_win_prob', 'implied_draw_prob', 
                         'implied_away_win_prob']]


# Print column names to ensure everything is added correctly
print(team_names.columns)

# Display the first few rows of the DataFrame
team_names.head()

Index(['home_team', 'away_team', 'true_results', 'predicted_results',
       'home_prob', 'draw_prob', 'away_prob', 'implied_home_win_prob',
       'implied_draw_prob', 'implied_away_win_prob'],
      dtype='object')


home_team    away_team true_results  predicted_results  home_prob  \
0    man city       bolton            H                  2   0.863720   
1     swansea     west ham            D                  0   0.337894   
2   liverpool   man united            D                  1   0.325423   
3       stoke  bournemouth            A                  1   0.100232   
4  sunderland   man united            A                  0   0.016920   

   draw_prob  away_prob  implied_home_win_prob  implied_draw_prob  \
0   0.048617   0.087662               0.404145           0.286010   
1   0.216486   0.445620               0.185958           0.273467   
2   0.512692   0.161885               0.391387           0.285412   
3   0.739900   0.159868               0.540575           0.273467   
4   0.020808   0.962272               0.323341           0.289997   

   implied_away_win_prob  
0               0.309845  
1               0.540575  
2               0.323201  
3               0.185958  
4               0.386662

In [11]:
# Define a function to calculate the Brier score
def calculate_brier_score(predictions, true_outcome):
    return np.mean((predictions - true_outcome) ** 2)

# Assuming you have the following DataFrame as `team_names`
# Add the one-hot encoded true predictions as a new column based on 'true_predictions'
def encode_result(result):
    # 'H' = [1, 0, 0], 'D' = [0, 1, 0], 'A' = [0, 0, 1]
    if result == 'H':
        return [1, 0, 0]
    elif result == 'D':
        return [0, 1, 0]
    elif result == 'A':
        return [0, 0, 1]

team_names['true_predictions_brier'] = team_names['true_results'].apply(encode_result)

# Now calculate the Brier score for each row using the predicted probabilities
team_names['brier_score_market'] = team_names.apply(
    lambda row: calculate_brier_score(np.array([row['home_prob'], row['draw_prob'], row['away_prob']]), row['true_predictions_brier']),
    axis=1
)

# calculate the brier score for the model
team_names['brier_score_model'] = team_names.apply(
    lambda row: calculate_brier_score(np.array([row['implied_home_win_prob'], row['implied_draw_prob'], row['implied_away_win_prob']]), row['true_predictions_brier']),
    axis=1
)


# Optionally, calculate the average Brier score for the entire dataset
average_brier_score_market = team_names['brier_score_market'].mean()

# Optionally, calculate the average Brier score for the entire dataset
average_brier_score_model = team_names['brier_score_model'].mean()


# encode predicted_results to H,D,A
def decode_result(result):
    if result == 2:
        return 'H'
    elif result == 1:
        return 'D'
    elif result == 0:
        return 'A'
    
team_names['predicted_results'] = team_names['predicted_results'].apply(decode_result)


# Display the Brier score for each row and the average Brier score
display(team_names[['home_team', 'away_team', 'true_results', 'predicted_results', 'brier_score_model', 'brier_score_market']])
print(f"Average Brier Score Market: {average_brier_score_market}")
print(f"Average Brier Score Model: {average_brier_score_model}")

home_team    away_team true_results predicted_results  \
0        man city       bolton            H                 H   
1         swansea     west ham            D                 A   
2       liverpool   man united            D                 D   
3           stoke  bournemouth            A                 D   
4      sunderland   man united            A                 A   
...           ...          ...          ...               ...   
1459    newcastle        stoke            H                 H   
1460  aston villa      everton            A                 A   
1461     man city  aston villa            H                 H   
1462       wolves      everton            A                 A   
1463      arsenal       fulham            H                 H   

      brier_score_model  brier_score_market  
0              0.177616        9.540162e-03  
1              0.284884        3.088812e-01  
2              0.256093        1.231918e-01  
3              0.343223        4.211067e-01  
4              0.188277        7.142293e-04  
...                 ...                 ...  
1459           0.095651        2.681501e-03  
1460           0.256851        1.572570e-02  
1461           0.151064        1.602832e-02  
1462           0.236278        5.616717e-02  
1463           0.127527        4.937550e-07  

[1464 rows x 6 columns]

Average Brier Score Market: 0.14535448948435145
Average Brier Score Model: 0.2311581039249381
